services:
  backend:
    build:
      context: ./
      dockerfile: docker/Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${{ secrets.DATABASE_URL }}
      - JWT_SECRET=${{ secrets.JWT_SECRET }}
      - PORT=3001
      - SALTROUNDS=${{ secrets.SALTROUNDS }}
      - FRONTEND_ORIGIN=${{ secrets.FRONTEND_ORIGIN }}
    depends_on:
      - db

  frontend:
    build:
      context: ./
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_HTTP_URL=${{ secrets.NEXT_PUBLIC_HTTP_URL }}
      - NEXT_PUBLIC_WS_URL=${{ secrets.NEXT_PUBLIC_WS_URL }}
    depends_on:
      - backend
      - ws
      - db

  ws:
    build:
      context: ./
      dockerfile: docker/Dockerfile.ws
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${{ secrets.DATABASE_URL }}
      - JWT_SECRET=${{ secrets.JWT_SECRET }}
      - PORT=8080
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: harshit
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: meetdraw
    ports:
      - "5432:5432"
volumes:
  postgres_data:
