name: Deploy the backend
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: joshipallava/meetdraw-be:${{ github.sha }}

      - name: Push to VM
        run: |
          echo "${{ secrets.SSH_SECRET }}" > ~/ssh_key
          mkdir -p ~/.ssh
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@${{ secrets.SSH_IP }} -t 'docker system prune -a -f && docker pull joshipallava/meetdraw-be:${{ github.sha }} && docker stop meetdraw_be && docker rm meetdraw_be && docker run --name meetdraw_be -e DATABASE_URL="${{ secrets.DATABASE_URL }}" -e SALTROUNDS=${{ secrets.SALTROUNDS }} -e JWT_SECRET=${{ secrets.JWT_SECRET }} -e PORT=${{ secrets.HTTP_PORT }} -e FRONTEND_ORIGIN="${{ secrets.FRONTEND_ORIGIN }}" -d -p 3001:3001 joshipallava/meetdraw-be:${{ github.sha }}'
