name: Deploy the ws
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.ws
          push: true
          tags: joshipallava/meetdraw-ws:${{ github.sha }}

      - name: Push to VM
        run: |
          echo "${{ secrets.SSH_SECRET }}" > ~/ssh_key
          mkdir -p ~/.ssh
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@${{ secrets.SSH_IP }} -t 'docker system prune -a -f && docker pull joshipallava/meetdraw-ws:${{ github.sha }} && docker stop meetdraw_ws && docker rm meetdraw_ws && docker run --name meetdraw_ws -e DATABASE_URL="${{ secrets.DATABASE_URL }}" -e JWT_SECRET=${{ secrets.JWT_SECRET }} -e PORT=${{ secrets.WS_PORT }} -d -p 8080:8080 joshipallava/meetdraw-ws:${{ github.sha }}'
